import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import  { Toaster } from 'react-hot-toast';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ESTORE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Global Toasts */}
        <Toaster
          position="top-center"
          reverseOrder={false}
          toastOptions={{
            duration: 3000,
            style: {
              borderRadius: "12px",
              padding: "14px 18px",
              fontSize: "14px",
              fontWeight: 500,
            },

            success: {
              style: {
                background: "#16a34a", // green-600
                color: "#ffffff",
              },
              iconTheme: {
                primary: "#ffffff",
                secondary: "#16a34a",
              },
            },

            error: {
              style: {
                background: "#dc2626", // red-600
                color: "#ffffff",
              },
              iconTheme: {
                primary: "#ffffff",
                secondary: "#dc2626",
              },
            },

            loading: {
              style: {
                background: "#1f2937", // gray-800
                color: "#ffffff",
              },
            },
          }}
        />

        <div className="mx-auto  p-4 sm:max-w-xl  md:max-w-2xl lg:max-w-6xl xl:max-w-7xl">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
